In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("./raw/budget/budget.csv")
data

                  Alcaldia      venta    Renta
0           Alvaro Obregón  6578833.0  15302.0
1             Azcapotzalco  2345500.0  12267.0
2            Benito Juarez  4855384.0  16429.0
3                 Coyoacán  5912716.0  13644.0
4    Cuajimalpa de Morelos  8081067.0  15641.0
5               Cuauhtémoc  5226536.0  22911.0
6        Gustavo A. Madero  5049058.0   9757.0
7                Iztacalco  2650977.0  10057.0
8               Iztapalapa  4150000.0  10459.0
9   La Magdalena Contreras  7575000.0  11671.0
10          Miguel Hidalgo  9794003.0  21326.0
11              Milpa Alta  3673255.0  16000.0
12                 Tláhuac  2651450.0  17938.0
13                 Tlalpan  4479429.0  16000.0
14     Venustiano Carranza  4675000.0  10316.0
15              Xochimilco  2992341.0  15183.0

In [6]:
for i in range(1,len(data.columns)):
    index=data.columns[i]
    data[index+"_PORCENTAJE_MUN"]=data[index]/data[index].max()
data

,Alcaldia,venta,Renta,venta_PORCENTAJE_MUN,Renta_PORCENTAJE_MUN
0,Alvaro Obregón,6578833.0,15302.0,0.671721,0.667889
1,Azcapotzalco,2345500.0,12267.0,0.239483,0.535420
2,Benito Juarez,4855384.0,16429.0,0.495751,0.717079
3,Coyoacán,5912716.0,13644.0,0.603708,0.595522
4,Cuajimalpa de Morelos,8081067.0,15641.0,0.825104,0.682685
5,Cuauhtémoc,5226536.0,22911.0,0.533647,1.000000
6,Gustavo A. Madero,5049058.0,9757.0,0.515525,0.425865
7,Iztacalco,2650977.0,10057.0,0.270673,0.438959
8,Iztapalapa,4150000.0,10459.0,0.423729,0.456506
9,La Magdalena Contreras,7575000.0,11671.0,0.773432,0.509406
10,Miguel Hidalgo,9794003.0,21326.0,1.000000,0.930819
11,Milpa Alta,3673255.0,16000.0,0.375051,0.698355
12,Tláhuac,2651450.0,17938.0,0.270722,0.782943
13,Tlalpan,4479429.0,16000.0,0.457364,0.698355
14,Venustiano Carranza,4675000.0,10316.0,0.477333,0.450264
15,Xochimilco,2992341.0,15183.0,0.305528,0.662695

In [7]:
data.to_csv("./output/budget.csv", index=False)