In [34]:
import pandas as pd
import numpy as np

### Hoteles

In [90]:
data = pd.read_csv("./raw/cultural_centers/establecimientos-de-hospedaje-2021.csv",encoding='latin-1')
data=data.iloc[:,3:6].drop(["CP"], axis=1)

In [91]:
data

                  ALCALDÍA       CATEGORÍA
0    Cuajimalpa de Morelos     5 Estrellas
1           Álvaro Obregón     5 Estrellas
2               Cuauhtémoc     5 Estrellas
3           Miguel Hidalgo     5 Estrellas
4            Benito Juárez     5 Estrellas
..                     ...             ...
629             Xochimilco  Sin Clasificar
630             Cuauhtémoc  Sin Clasificar
631         Miguel Hidalgo  Sin Clasificar
632          Benito Juárez  Sin Clasificar
633             Cuauhtémoc  Sin Clasificar

[634 rows x 2 columns]

In [92]:
data['CATEGORÍA'] = data['CATEGORÍA'].str.replace(' Estrellas', '', regex=False)
data['CATEGORÍA'] = data['CATEGORÍA'].str.replace(' estrellas', '', regex=False)
data['CATEGORÍA'] = data['CATEGORÍA'].str.replace(' Estrella', '', regex=False)
data['CATEGORÍA'] = data['CATEGORÍA'].replace('Sin Clasificar', np.nan)

In [93]:
data["CATEGORÍA"]=pd.to_numeric(data["CATEGORÍA"], errors="coerce")

In [94]:
data=data.groupby("ALCALDÍA")["CATEGORÍA"].mean()
data

ALCALDÍA
Azcapotzalco             2.454545
Benito Juárez            3.488889
Coyoacán                 3.909091
Cuajimalpa de Morelos    4.444444
Cuauhtémoc               2.881988
Gustavo A. Madero        2.580645
Iztacalco                3.384615
Iztapalapa               3.000000
Magdalena Contreras      5.000000
Miguel Hidalgo           3.549020
Tlalpan                  3.500000
Tláhuac                  4.000000
Venustiano Carranza      3.000000
Xochimilco               3.200000
Álvaro Obregón           4.384615
Name: CATEGORÍA, dtype: float64

In [95]:
df_to_save = data.reset_index()

df_to_save.columns = ['ALCALDÍA', 'CATEGORIA_PROMEDIO']

In [98]:
df_to_save.to_csv("./output/hotels.csv", index=False)

### Servicios turisticos

In [100]:
data = pd.read_csv("./raw/cultural_centers/prestadores-de-servicios-turisticos-de-la-ciudad-de-mexico.csv")
data

,id,tipo,nombre,calle_y_numero,colonia,alcaldia,cp,categoria,subcategoria
0,0,Agencia de viajes,Agencia de Viajes México Kanko,"Av.Paseo de La Reforma, No.393",Juárez,Cuauhtémoc,6500.0,NaN,NaN
1,1,Agencia de viajes,Viajes Zeta,Rio Marne 19-405,Renacimiento,Cuauhtémoc,6500.0,NaN,NaN
2,2,Agencia de viajes,In Fact,Rio Sena 82,Cuauhtémoc,Cuauhtémoc,6500.0,NaN,NaN
3,3,Agencia de viajes,Sistema Moderno de Viajes,Liverpool 143 interior 202,Juárez,Cuauhtémoc,6600.0,NaN,NaN
4,4,Agencia de viajes,Integradores Bts,Rodolfo Gaona 81 piso 1,Lomas de Sotelo,Miguel Hidalgo,11200.0,Mayorista,NaN
...,...,...,...,...,...,...,...,...,...
2507,2507,Turismo alternativo,Servicios Turísticos Xochiquetzalli,Violetas 72,Barrio de Santa Crucita,Xochimilco,16070.0,Operadora,NaN
2508,2508,Turismo alternativo,Parque ecoturístico de la comunidad de San Ber...,Ojo de Agua 1005 bienes comunales San Bernabé ...,San Bernabé Ocotepec,La Magdalena Contreras,10369.0,Operadora,NaN
2509,2509,Turismo alternativo,Hangar Tours 4X4,Avenida Tres 62,San Pedro de los Pinos,Benito Juárez,3800.0,Operadora,NaN
2510,2510,Turismo alternativo,Original Extreme Experience,Alejandro Dumas 145,Polanco IV sección,Miguel Hidalgo,11550.0,Operadora,NaN
2511,2511,Turismo alternativo,Marketing y Aventura,Geranio 130,Atlampa,Cuauhtémoc,6450.0,Operadora,NaN

In [101]:
data_tipo=data["tipo"]
data_alcaldia=data["alcaldia"]

In [119]:
data_restaurantes=pd.concat([data_alcaldia,data_tipo], axis=1)
data_restaurantes

                    alcaldia                 tipo
0                 Cuauhtémoc    Agencia de viajes
1                 Cuauhtémoc    Agencia de viajes
2                 Cuauhtémoc    Agencia de viajes
3                 Cuauhtémoc    Agencia de viajes
4             Miguel Hidalgo    Agencia de viajes
...                      ...                  ...
2507              Xochimilco  Turismo alternativo
2508  La Magdalena Contreras  Turismo alternativo
2509           Benito Juárez  Turismo alternativo
2510          Miguel Hidalgo  Turismo alternativo
2511              Cuauhtémoc  Turismo alternativo

[2512 rows x 2 columns]

In [120]:
data_restaurantes=data_restaurantes.query('tipo=="Restaurante"').replace('Restaurante', int(1), regex=False)

In [121]:
data_restaurantes=data_restaurantes.groupby("alcaldia")["tipo"].sum()

In [122]:
data_restaurantes

alcaldia
Azcapotzalco               27
Benito Juárez             121
Coyoacán                   73
Cuajimalpa de Morelos      27
Cuauhtémoc                244
Gustavo A. Madero          42
Iztacalco                   5
Iztapalapa                 32
La Magdalena Contreras      7
Miguel Hidalgo            147
Milpa Alta                  3
Tlalpan                    37
Tláhuac                     6
Venustiano Carranza        21
Xochimilco                  5
Álvaro Obregón             88
Name: tipo, dtype: int64

In [123]:
df_to_save = data_restaurantes.reset_index()

df_to_save.columns = ['alcaldia', 'tipo']
df_to_save

                  alcaldia  tipo
0             Azcapotzalco    27
1            Benito Juárez   121
2                 Coyoacán    73
3    Cuajimalpa de Morelos    27
4               Cuauhtémoc   244
5        Gustavo A. Madero    42
6                Iztacalco     5
7               Iztapalapa    32
8   La Magdalena Contreras     7
9           Miguel Hidalgo   147
10              Milpa Alta     3
11                 Tlalpan    37
12                 Tláhuac     6
13     Venustiano Carranza    21
14              Xochimilco     5
15          Álvaro Obregón    88

In [124]:
df_to_save["tipo"]=df_to_save["tipo"]/df_to_save["tipo"].sum()

In [125]:
df_to_save

                  alcaldia      tipo
0             Azcapotzalco  0.030508
1            Benito Juárez  0.136723
2                 Coyoacán  0.082486
3    Cuajimalpa de Morelos  0.030508
4               Cuauhtémoc  0.275706
5        Gustavo A. Madero  0.047458
6                Iztacalco  0.005650
7               Iztapalapa  0.036158
8   La Magdalena Contreras  0.007910
9           Miguel Hidalgo  0.166102
10              Milpa Alta  0.003390
11                 Tlalpan  0.041808
12                 Tláhuac  0.006780
13     Venustiano Carranza  0.023729
14              Xochimilco  0.005650
15          Álvaro Obregón  0.099435

In [126]:
df_to_save.to_csv("./output/restaurant.csv", index=False)

### Centro cultural

In [132]:
data = pd.read_csv("./raw/cultural_centers/evaluacion_distancia_equipamientos_cultural_cdmx_2020_42.csv")
data

,Alcaldía,Distancia promedio a un equipamiento de cultura,Cobertura de equipamiento de cultural
0,Álvaro Obregón,2037.25,18.82
1,Azcapotzalco,1964.77,12.30
2,Benito Juárez,724.83,77.04
3,Coyoacán,1195.93,39.68
4,Cuajimalpa de Morelos,2286.37,9.30
5,Cuauhtémoc,449.16,95.45
6,Gustavo A. Madero,3356.73,15.04
7,Iztacalco,2572.28,11.47
8,Iztapalapa,2155.12,15.03
9,La Magdalena Contreras,1841.13,25.27
10,Miguel Hidalgo,821.86,73.43
11,Milpa Alta,1665.16,29.65
12,Tláhuac,1568.61,30.92
13,Tlalpan,2486.19,14.71
14,Venustiano Carranza,2237.93,15.76
15,Xochimilco,1690.79,27.79

In [133]:
data.to_csv("./output/culture.csv", index=False)

### Deporte

In [134]:
data = pd.read_csv("./raw/cultural_centers/evaluacion_distancia_equipamientos_deportivo_cdmx_2020_43.csv")
data

,Alcaldía,Distancia promedio a un equipamiento deportivo,Cobertura de equipamiento deportivo a una distancia de 15 min caminando
0,Álvaro Obregón,852.55,71.11
1,Azcapotzalco,673.54,83.08
2,Benito Juárez,587.59,94.50
3,Coyoacán,707.40,82.10
4,Cuajimalpa de Morelos,713.17,78.80
5,Cuauhtémoc,549.85,91.24
6,Gustavo A. Madero,871.17,69.33
7,Iztacalco,598.37,90.00
8,Iztapalapa,858.39,71.62
9,La Magdalena Contreras,348.28,99.08
10,Miguel Hidalgo,585.36,90.13
11,Milpa Alta,2023.80,35.92
12,Tláhuac,812.74,75.57
13,Tlalpan,811.20,80.07
14,Venustiano Carranza,604.60,93.23
15,Xochimilco,847.12,72.83

In [135]:
data.to_csv("./output/sport.csv", index=False)