In [1]:
import pandas as pd

In [7]:
data = pd.read_csv("./raw/green_spaces/areas_verdes.csv")
data

,Alcaldía,Habitantes (Año 2015),Superficie (m²),Superficie por habitante (m²)
0,Total de la entidad Ciudad de México,8918653.0,67311573.8,7.5
1,Azcapotzalco,400161.0,3980866.7,9.9
2,Coyoacán,608479.0,9157547.7,15.0
3,Cuajimalpa de Morelos,199224.0,2048957.7,10.3
4,Gustavo A. Madero,1164477.0,7851619.6,6.7
5,Iztacalco,390348.0,1944289.0,5.0
6,Iztapalapa,1827868.0,9834858.6,5.4
7,La Magdalena Contreras,243886.0,1335114.4,5.5
8,Milpa Alta,137927.0,309724.0,2.2
9,Álvaro Obregón,749982.0,4913463.7,6.6
10,Tláhuac,361593.0,3054084.7,8.4
11,Tlalpan,677104.0,6530744.7,9.6
12,Xochimilco,415933.0,2092259.6,5.0
13,Benito Juárez,417416.0,929230.8,2.2
14,Cuauhtémoc,532553.0,1915961.0,3.6
15,Miguel Hidalgo,364439.0,5607701.5,15.4
16,Venustiano Carranza,427263.0,5805150.1,13.6

In [8]:
for i in range(1,len(data.columns)-1):
    index=data.columns[i]
    data[index+"_PORCENTAJE"]=data[index]/data[index][0]
data

,Alcaldía,Habitantes (Año 2015),Superficie (m²),Superficie por habitante (m²),Habitantes (Año 2015)_PORCENTAJE,Superficie (m²)_PORCENTAJE
0,Total de la entidad Ciudad de México,8918653.0,67311573.8,7.5,1.000000,1.000000
1,Azcapotzalco,400161.0,3980866.7,9.9,0.044868,0.059141
2,Coyoacán,608479.0,9157547.7,15.0,0.068225,0.136047
3,Cuajimalpa de Morelos,199224.0,2048957.7,10.3,0.022338,0.030440
4,Gustavo A. Madero,1164477.0,7851619.6,6.7,0.130566,0.116646
5,Iztacalco,390348.0,1944289.0,5.0,0.043768,0.028885
6,Iztapalapa,1827868.0,9834858.6,5.4,0.204949,0.146109
7,La Magdalena Contreras,243886.0,1335114.4,5.5,0.027346,0.019835
8,Milpa Alta,137927.0,309724.0,2.2,0.015465,0.004601
9,Álvaro Obregón,749982.0,4913463.7,6.6,0.084091,0.072996
10,Tláhuac,361593.0,3054084.7,8.4,0.040543,0.045372
11,Tlalpan,677104.0,6530744.7,9.6,0.075920,0.097023
12,Xochimilco,415933.0,2092259.6,5.0,0.046636,0.031083
13,Benito Juárez,417416.0,929230.8,2.2,0.046803,0.013805
14,Cuauhtémoc,532553.0,1915961.0,3.6,0.059712,0.028464
15,Miguel Hidalgo,364439.0,5607701.5,15.4,0.040863,0.083310
16,Venustiano Carranza,427263.0,5805150.1,13.6,0.047907,0.086243

In [9]:
data.to_csv("./output/green_spaces.csv", index=False)