In [47]:
import pandas as pd

### History and Culture

In [41]:
data = pd.read_csv("./raw/life_style/historic.csv")
data_transposed = data.T
data_transposed=data_transposed.iloc[1:,:]
data_transposed["HISTORIC_SUM"]=data_transposed.sum(axis=1)
data_transposed["HISTORIC_PERCENTAGE"]=data_transposed["HISTORIC_SUM"]/data_transposed["HISTORIC_SUM"].sum()
df = data_transposed["HISTORIC_PERCENTAGE"].reset_index().rename(columns={'index': 'ALCALDIA'})
df=df.sort_values(by="ALCALDIA")
df.to_csv("./output/culture.csv", index=False)

In [42]:
df

                  ALCALDIA  HISTORIC_PERCENTAGE
8             Azcapotzalco             0.023227
14           Benito Juárez             0.080685
4                 Coyoacán             0.083130
13   Cuajimalpa de Morelos             0.008557
0               Cuauhtémoc             0.282396
1        Gustavo A. Madero             0.068460
11               Iztacalco             0.026895
2               Iztapalapa             0.081907
6   La Magdalena Contreras             0.012225
7           Miguel Hidalgo             0.130807
15              Milpa Alta             0.023227
3                  Tlalpan             0.040342
10                 Tláhuac             0.036675
5      Venustiano Carranza             0.026895
9               Xochimilco             0.030562
12          Álvaro Obregón             0.044010

### Sport

In [46]:
data = pd.read_csv("./raw/life_style/sport_centers.csv")
data_transposed = data.T
data_transposed=data_transposed.iloc[1:,:]
data_transposed["HISTORIC_SUM"]=data_transposed.sum(axis=1)
data_transposed["HISTORIC_PERCENTAGE"]=data_transposed["HISTORIC_SUM"]/data_transposed["HISTORIC_SUM"].sum()
df = data_transposed["HISTORIC_PERCENTAGE"].reset_index().rename(columns={'index': 'ALCALDIA'})
df=df.sort_values(by="ALCALDIA")
df.to_csv("./output/sport.csv", index=False)

In [45]:
df

                  ALCALDIA  HISTORIC_PERCENTAGE
8             Azcapotzalco             0.036755
14           Benito Juárez             0.058302
4                 Coyoacán             0.060414
13   Cuajimalpa de Morelos             0.026616
0               Cuauhtémoc             0.072243
1        Gustavo A. Madero             0.132235
11               Iztacalco             0.040558
2               Iztapalapa             0.180820
6   La Magdalena Contreras             0.031263
7           Miguel Hidalgo             0.048585
15              Milpa Alta             0.017744
3                  Tlalpan             0.074356
10                 Tláhuac             0.046895
5      Venustiano Carranza             0.042670
9               Xochimilco             0.053654
12          Álvaro Obregón             0.076891

### Recreational

In [48]:
data = pd.read_csv("./raw/life_style/recreational.csv")
data_transposed = data.T
data_transposed=data_transposed.iloc[1:,:]
data_transposed["HISTORIC_SUM"]=data_transposed.sum(axis=1)
data_transposed["HISTORIC_PERCENTAGE"]=data_transposed["HISTORIC_SUM"]/data_transposed["HISTORIC_SUM"].sum()
df = data_transposed["HISTORIC_PERCENTAGE"].reset_index().rename(columns={'index': 'ALCALDIA'})
df=df.sort_values(by="ALCALDIA")
df.to_csv("./output/recreation.csv", index=False)