In [60]:
import pandas as pd

In [63]:
data = pd.read_csv("./raw/education/escuelas en la zona metropolitana.xlsx - Totales de escuela.csv")
data

,ciclo_esc,ent,alc,tipo_educ,niv_educ,Numero de escuelas,h_alum,m_alum,tot_alum,h_prof,m_prof,tot_profesores
0,2017-2018,Ciudad de México,Azcapotzalco,Básica,Primaria,149,18257,17527,35784,148,1335,1483
1,2017-2018,Ciudad de México,Azcapotzalco,Básica,Secundaria,60,9735,8905,18640,511,929,1440
2,2017-2018,Ciudad de México,Azcapotzalco,Media Superior,Bachillerato,30,21464,20449,41913,1355,1220,2575
3,2017-2018,Ciudad de México,Azcapotzalco,Superior,Licenciatura Universitaria Tecnológica,9,19120,9440,28560,0,0,2241
4,2017-2018,Ciudad de México,Azcapotzalco,Superior,Normal Licenciatura,1,295,717,1012,0,0,221
...,...,...,...,...,...,...,...,...,...,...,...,...
487,2021-2022,Ciudad de México,Álvaro Obregón,Media Superior,Bachillerato,55,21584,21591,43175,1832,1824,3656
488,2021-2022,Ciudad de México,Álvaro Obregón,Superior,Licenciatura Universitaria Tecnológica,39,13008,13826,26834,0,0,2566
489,2021-2022,Ciudad de México,Álvaro Obregón,Superior,Normal Licenciatura,1,2,890,892,0,0,121
490,2021-2022,Ciudad de México,Álvaro Obregón,Superior,Posgrado,36,2026,2480,4506,0,0,1058
491,2021-2022,Ciudad de México,Álvaro Obregón,Superior,Técnico Superior,5,223,238,461,0,0,59

In [74]:
data=data[["ent","alc","tipo_educ","Numero de escuelas"]]
data

                  ent             alc       tipo_educ  Numero de escuelas
0    Ciudad de México    Azcapotzalco          Básica                 149
1    Ciudad de México    Azcapotzalco          Básica                  60
2    Ciudad de México    Azcapotzalco  Media Superior                  30
3    Ciudad de México    Azcapotzalco        Superior                   9
4    Ciudad de México    Azcapotzalco        Superior                   1
..                ...             ...             ...                 ...
487  Ciudad de México  Álvaro Obregón  Media Superior                  55
488  Ciudad de México  Álvaro Obregón        Superior                  39
489  Ciudad de México  Álvaro Obregón        Superior                   1
490  Ciudad de México  Álvaro Obregón        Superior                  36
491  Ciudad de México  Álvaro Obregón        Superior                   5

[492 rows x 4 columns]

In [ ]:
data=data.query('ent=="Ciudad de México"')

                  ent             alc       tipo_educ  Numero de escuelas
0    Ciudad de México    Azcapotzalco          Básica                 149
1    Ciudad de México    Azcapotzalco          Básica                  60
2    Ciudad de México    Azcapotzalco  Media Superior                  30
3    Ciudad de México    Azcapotzalco        Superior                   9
4    Ciudad de México    Azcapotzalco        Superior                   1
..                ...             ...             ...                 ...
487  Ciudad de México  Álvaro Obregón  Media Superior                  55
488  Ciudad de México  Álvaro Obregón        Superior                  39
489  Ciudad de México  Álvaro Obregón        Superior                   1
490  Ciudad de México  Álvaro Obregón        Superior                  36
491  Ciudad de México  Álvaro Obregón        Superior                   5

[492 rows x 4 columns]

In [77]:
data=data.drop(['ent'], axis=1)

In [135]:
data_educación_basica = data[data["tipo_educ"].isin(["Básica", "Media Superior"])]
data_educación_basica= data_educación_basica.groupby("alc", as_index=False)["Numero de escuelas"].sum()
data_educación_basica.rename(columns={'alc': 'ALCALDIA', 'Numero de escuelas': 'NO_ESCUELAS_BASICAS'}, inplace=True)
data_educación_basica

                  ALCALDIA  NO_ESCUELAS_BASICAS
0             Azcapotzalco                 1155
1            Benito Juárez                 1346
2                 Coyoacán                 1679
3    Cuajimalpa de Morelos                  857
4               Cuauhtémoc                 1737
5        Gustavo A. Madero                 3651
6                Iztacalco                 1149
7               Iztapalapa                 4241
8   La Magdalena Contreras                  575
9           Miguel Hidalgo                 1273
10              Milpa Alta                  391
11                 Tlalpan                 1838
12                 Tláhuac                  873
13     Venustiano Carranza                 1228
14              Xochimilco                 1051
15          Álvaro Obregón                 1931

In [136]:
data_educación_superior = data[data["tipo_educ"].isin(["Superior"])]
data_educación_superior= data_educación_superior.groupby("alc", as_index=False)["Numero de escuelas"].sum()
data_educación_superior.rename(columns={'alc': 'NOS', 'Numero de escuelas': 'NO_ESCUELAS_SUPERIORES'}, inplace=True)
data_educación_superior

                       NOS  NO_ESCUELAS_SUPERIORES
0             Azcapotzalco                     116
1            Benito Juárez                     379
2                 Coyoacán                     458
3    Cuajimalpa de Morelos                      63
4               Cuauhtémoc                     754
5        Gustavo A. Madero                     428
6                Iztacalco                      82
7               Iztapalapa                     212
8   La Magdalena Contreras                      37
9           Miguel Hidalgo                     325
10              Milpa Alta                      19
11                 Tlalpan                     329
12                 Tláhuac                      30
13     Venustiano Carranza                      23
14              Xochimilco                      26
15          Álvaro Obregón                     411

In [137]:
numero_escuelas=pd.concat([data_educación_basica, data_educación_superior], axis=1)
numero_escuelas=numero_escuelas.drop('NOS',axis=1)

In [138]:
new_row_df = pd.DataFrame({"ALCALDIA": ["Total de la entidad Ciudad de México"], "NO_ESCUELAS_BASICAS": [numero_escuelas["NO_ESCUELAS_BASICAS"].sum()],"NO_ESCUELAS_SUPERIORES": [numero_escuelas["NO_ESCUELAS_SUPERIORES"].sum()] })
numero_escuelas = pd.concat([new_row_df,numero_escuelas], ignore_index=False).reset_index().drop("index",axis=1)
numero_escuelas

,ALCALDIA,NO_ESCUELAS_BASICAS,NO_ESCUELAS_SUPERIORES
0,Total de la entidad Ciudad de México,24975,3692
1,Azcapotzalco,1155,116
2,Benito Juárez,1346,379
3,Coyoacán,1679,458
4,Cuajimalpa de Morelos,857,63
5,Cuauhtémoc,1737,754
6,Gustavo A. Madero,3651,428
7,Iztacalco,1149,82
8,Iztapalapa,4241,212
9,La Magdalena Contreras,575,37
10,Miguel Hidalgo,1273,325
11,Milpa Alta,391,19
12,Tlalpan,1838,329
13,Tláhuac,873,30
14,Venustiano Carranza,1228,23
15,Xochimilco,1051,26
16,Álvaro Obregón,1931,411

In [139]:
total_municipal=numero_escuelas.iloc[:,1:].sum(axis=1)
for i in range(1,len(numero_escuelas.columns)):
    index=numero_escuelas.columns[i]
    numero_escuelas[index+"_PORCENTAJE_MUN"]=numero_escuelas[index]/total_municipal
numero_escuelas

,ALCALDIA,NO_ESCUELAS_BASICAS,NO_ESCUELAS_SUPERIORES,NO_ESCUELAS_BASICAS_PORCENTAJE_MUN,NO_ESCUELAS_SUPERIORES_PORCENTAJE_MUN
0,Total de la entidad Ciudad de México,24975,3692,0.871211,0.128789
1,Azcapotzalco,1155,116,0.908733,0.091267
2,Benito Juárez,1346,379,0.780290,0.219710
3,Coyoacán,1679,458,0.785681,0.214319
4,Cuajimalpa de Morelos,857,63,0.931522,0.068478
5,Cuauhtémoc,1737,754,0.697310,0.302690
6,Gustavo A. Madero,3651,428,0.895072,0.104928
7,Iztacalco,1149,82,0.933387,0.066613
8,Iztapalapa,4241,212,0.952392,0.047608
9,La Magdalena Contreras,575,37,0.939542,0.060458
10,Miguel Hidalgo,1273,325,0.796621,0.203379
11,Milpa Alta,391,19,0.953659,0.046341
12,Tlalpan,1838,329,0.848177,0.151823
13,Tláhuac,873,30,0.966777,0.033223
14,Venustiano Carranza,1228,23,0.981615,0.018385
15,Xochimilco,1051,26,0.975859,0.024141
16,Álvaro Obregón,1931,411,0.824509,0.175491

In [140]:
numero_escuelas.to_csv("./output/schools.csv", index=False)