In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("./raw/security/conjunto_de_datos_ensu_cb_0625.csv")

In [10]:
df=df[["NOM_ENT","NOM_MUN","BP1_2_01","BP1_2_03","BP1_4_1","BP1_4_2","BP1_4_3","BP1_4_4","BP1_4_5","BP1_4_6","BP1_4_7","BP1_4_8","BP1_5_1","BP1_5_2","BP1_6_4","BP2_2_03","BP2_2_11","BP2_2_14","BP3_1_05","BP3_1_07","BP3_1_08","BP3_1_10","BP3_1_11","BP3_1_13","BP3_1_14","BP4_1_1","BP4_1_2","BP4_1_3","BP4_1_7","BP4_1_8"]]
df

,NOM_ENT,NOM_MUN,BP1_2_01,BP1_2_03,BP1_4_1,BP1_4_2,BP1_4_3,BP1_4_4,BP1_4_5,BP1_4_6,...,BP3_1_08,BP3_1_10,BP3_1_11,BP3_1_13,BP3_1_14,BP4_1_1,BP4_1_2,BP4_1_3,BP4_1_7,BP4_1_8
0,AGUASCALIENTES,AGUASCALIENTES,2,2,1,1,1,1,1,1,...,0,0,0,0,1,2,2,2,2,2
1,AGUASCALIENTES,AGUASCALIENTES,1,2,2,2,1,1,2,2,...,1,1,0,0,1,1,2,2,2,1
2,AGUASCALIENTES,AGUASCALIENTES,1,1,2,2,2,1,2,2,...,0,0,0,1,1,2,2,2,2,2
3,AGUASCALIENTES,AGUASCALIENTES,1,1,1,1,1,1,1,2,...,1,0,0,1,1,2,2,2,2,2
4,AGUASCALIENTES,AGUASCALIENTES,1,1,2,2,2,2,2,2,...,0,0,0,1,1,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23712,ZACATECAS,ZACATECAS,1,2,2,2,2,2,2,2,...,1,1,1,1,1,2,2,2,2,2
23713,ZACATECAS,ZACATECAS,1,2,2,2,2,2,2,9,...,0,1,0,0,1,2,2,2,2,2
23714,ZACATECAS,ZACATECAS,1,1,2,2,2,2,2,2,...,0,1,1,0,1,2,2,2,2,2
23715,ZACATECAS,ZACATECAS,1,2,2,2,1,2,2,1,...,0,1,1,1,1,2,2,2,2,2
23716,ZACATECAS,ZACATECAS,1,2,1,2,2,2,2,2,...,0,0,0,0,0,2,2,2,2,2

In [11]:
df=df.query('NOM_ENT=="CIUDAD DE MEXICO"').reset_index()
df = df.applymap(lambda x: 3 if isinstance(x, (int, float)) and x > 3 else x)

In [ ]:
df=df.drop("index",axis=1)
df=df.drop("NOM_ENT",axis=1)

,NOM_MUN,BP1_2_01,BP1_2_03,BP1_4_1,BP1_4_2,BP1_4_3,BP1_4_4,BP1_4_5,BP1_4_6,BP1_4_7,...,BP3_1_08,BP3_1_10,BP3_1_11,BP3_1_13,BP3_1_14,BP4_1_1,BP4_1_2,BP4_1_3,BP4_1_7,BP4_1_8
0,AZCAPOTZALCO,1,2,2,1,2,2,1,1,2,...,1,1,1,0,1,2,2,2,2,2
1,AZCAPOTZALCO,1,1,2,1,2,1,1,1,2,...,1,1,1,0,1,2,2,2,2,1
2,AZCAPOTZALCO,2,2,1,1,1,1,1,1,2,...,1,1,1,1,1,2,2,2,2,2
3,AZCAPOTZALCO,1,2,1,1,1,1,1,1,2,...,0,1,1,1,0,2,2,2,2,2
4,AZCAPOTZALCO,1,2,1,1,1,1,2,1,2,...,0,1,0,0,0,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4246,VENUSTIANO CARRANZA,1,2,2,2,2,2,2,2,2,...,1,1,0,0,0,2,2,2,2,2
4247,VENUSTIANO CARRANZA,1,1,2,2,2,2,2,2,2,...,0,1,0,0,0,2,2,2,2,2
4248,VENUSTIANO CARRANZA,1,2,2,1,2,1,1,2,2,...,1,1,1,0,0,2,2,2,2,2
4249,VENUSTIANO CARRANZA,1,2,2,1,2,2,2,2,2,...,1,1,1,1,0,2,2,2,2,2
4250,VENUSTIANO CARRANZA,1,2,1,1,1,1,1,2,3,...,1,1,1,0,0,2,2,2,2,2

In [15]:
df=df.groupby("NOM_MUN").mean().round().reset_index()
df

,NOM_MUN,BP1_2_01,BP1_2_03,BP1_4_1,BP1_4_2,BP1_4_3,BP1_4_4,BP1_4_5,BP1_4_6,BP1_4_7,...,BP3_1_08,BP3_1_10,BP3_1_11,BP3_1_13,BP3_1_14,BP4_1_1,BP4_1_2,BP4_1_3,BP4_1_7,BP4_1_8
0,ALVARO OBREGON,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,...,1.0,1.0,1.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
1,AZCAPOTZALCO,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,...,0.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
2,BENITO JUAREZ,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
3,COYOACAN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
4,CUAJIMALPA DE MORELOS,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
5,CUAUHTEMOC,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
6,GUSTAVO A. MADERO,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,0.0,1.0,2.0,2.0,2.0,2.0,2.0
7,IZTACALCO,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,...,1.0,1.0,1.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
8,IZTAPALAPA,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,...,0.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
9,LA MAGDALENA CONTRERAS,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,1.0,0.0,2.0,2.0,2.0,2.0,2.0
10,MIGUEL HIDALGO,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
11,MILPA ALTA,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,1.0,0.0,2.0,2.0,2.0,2.0,2.0
12,TLAHUAC,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,...,1.0,1.0,1.0,0.0,1.0,2.0,2.0,2.0,2.0,2.0
13,TLALPAN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
14,VENUSTIANO CARRANZA,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
15,XOCHIMILCO,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,...,1.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0

In [17]:
df.to_csv("./output/security.csv", index=False)